CREATE TABLE `BanList` (
`id` INT( 10 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 30 ) NOT NULL ,
`reason` VARCHAR( 125 ) NOT NULL,
`myIP` VARCHAR( 50 ) NOT NULL,
`mBy` VARCHAR( 30 ) NOT NULL
) ENGINE = innodb;